// Generates Sources/SwifttyCore/Unicode/Tables.swift.
//
// Widths follow wcwidth conventions: zero for nonspacing/enclosing marks,
// format characters (except prepended concatenation marks) and Hangul
// medial/final jamo; two for East Asian
// Wide/Fullwidth and emoji-presentation scalars; one otherwise.
//
// Usage: swift Scripts/gen-unicode-tables.swift [EastAsianWidth.txt]
import Foundation

let source = CommandLine.arguments.count > 1
    ? URL(fileURLWithPath: CommandLine.arguments[1])
    : URL(string: "https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt")!
let text = try String(contentsOf: source, encoding: .utf8)

var version = "unknown"
var wide = [Bool](repeating: false, count: 0x110000)
for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
    if line.hasPrefix("# EastAsianWidth-") {
        version = line.dropFirst(17).components(separatedBy: ".txt")[0]
    }
    let body = line.prefix { $0 != "#" }
    let fields = body.split(separator: ";").map { $0.trimmingCharacters(in: .whitespaces) }
    guard fields.count == 2, fields[1] == "W" || fields[1] == "F" else { continue }
    let bounds = fields[0].split(separator: ".").filter { !$0.isEmpty }.map { UInt32($0, radix: 16)! }
    for cp in bounds[0]...bounds.last! { wide[Int(cp)] = true }
}

// Prepended_Concatenation_Mark (PropList.txt): format characters that
// display, so wcwidth (and Ghostty) gives them one column.
let prependedConcatenationMarks: Set<UInt32> = Set(Array(0x0600...0x0605) + [0x06DD, 0x070F, 0x0890, 0x0891, 0x08E2, 0x110BD, 0x110CD])

var zero = [Bool](repeating: false, count: 0x110000)
for cp in 0..<0x110000 {
    guard let scalar = Unicode.Scalar(UInt32(cp)) else { continue }
    let props = scalar.properties
    switch props.generalCategory {
    case .nonspacingMark, .enclosingMark: zero[cp] = true
    case .format: zero[cp] = cp != 0x00AD && !prependedConcatenationMarks.contains(UInt32(cp))
    default: break
    }
    if (0x1160...0x11FF).contains(cp) || (0xD7B0...0xD7FF).contains(cp) { zero[cp] = true }
    if props.isEmojiPresentation { wide[cp] = true }
    if zero[cp] { wide[cp] = false }
}

func ranges(_ set: [Bool]) -> [(UInt32, UInt32)] {
    var out: [(UInt32, UInt32)] = []
    var cp = 0
    while cp < set.count {
        guard set[cp] else { cp += 1; continue }
        let start = cp
        while cp + 1 < set.count, set[cp + 1] { cp += 1 }
        out.append((UInt32(start), UInt32(cp)))
        cp += 1
    }
    return out
}

func emit(_ name: String, _ list: [(UInt32, UInt32)]) {
    print("    /// \(list.count) inclusive ranges, flattened as `[lo, hi, lo, hi, ...]`.")
    print("    static let \(name): [UInt32] = [")
    var row: [String] = []
    for (lo, hi) in list {
        row.append(String(format: "0x%05X, 0x%05X", lo, hi))
        if row.count == 4 { print("        " + row.joined(separator: ", ") + ","); row = [] }
    }
    if !row.isEmpty { print("        " + row.joined(separator: ", ") + ",") }
    print("    ]")
}

// Two-stage lookup table: stage 1 maps `scalar >> 8` to a deduplicated
// 256-entry block in stage 2. Stage 2 is emitted as a StaticString of ASCII
// digits '0'/'1'/'2' so it lives in the binary's constant data and costs
// nothing at startup.
var widths = [UInt8](repeating: 1, count: 0x110000)
for cp in 0 ..< 0x110000 {
    if wide[cp] { widths[cp] = 2 }
    if zero[cp] { widths[cp] = 0 }
}
var stage1: [Int] = []
var stage2: [UInt8] = []
var seen: [[UInt8]: Int] = [:]
for block in 0 ..< 0x1100 {
    let slice = Array(widths[block << 8 ..< (block + 1) << 8])
    if let index = seen[slice] {
        stage1.append(index)
    } else {
        seen[slice] = stage2.count >> 8
        stage1.append(stage2.count >> 8)
        stage2.append(contentsOf: slice)
    }
}

print("// Generated by Scripts/gen-unicode-tables.swift from EastAsianWidth-\(version). Do not edit.")
print("// swiftlint:disable all")
print("")
print("enum UnicodeTables {")
print("    static let version = \"\(version)\"")
print("")
emit("zeroWidth", ranges(zero))
print("")
emit("wide", ranges(wide))
print("")
print("    /// Block index for each 256-scalar block (\(stage1.count) entries).")
print("    static let stage1: [UInt16] = [")
for chunk in stride(from: 0, to: stage1.count, by: 16) {
    print("        " + stage1[chunk ..< min(chunk + 16, stage1.count)].map { String($0) }.joined(separator: ", ") + ",")
}
print("    ]")
print("")
print("    /// \(stage2.count >> 8) unique blocks of widths as ASCII digits.")
print("    static let stage2: StaticString = \"" + String(decoding: stage2.map { $0 + 0x30 }, as: UTF8.self) + "\"")
print("}")
