// Generates Sources/SwifttyCore/Terminal/GraphemeBreakTables.swift (default)
// or Tests/SwifttyCoreTests/GraphemeBreakTestData.swift (`--test-data`).
//
// The per-scalar properties replicate Ghostty's unicode props table
// (src/unicode/props_uucode.zig, built by the `uucode` package):
//
//   grapheme_break          uucode `grapheme_break_no_control`: UAX #29
//                           Grapheme_Cluster_Break refined with
//                           Indic_Conjunct_Break, Extended_Pictographic and
//                           Emoji_Modifier(_Base); Control/CR/LF fold to Other.
//   width_zero_in_grapheme  uucode `wcwidth_zero_in_grapheme` (see below).
//   emoji_vs_base           scalars with a "text style" (FE0E) line in
//                           emoji-variation-sequences.txt.
//
// Usage:
//   swift Scripts/gen-grapheme-tables.swift <ucd-dir> > Sources/SwifttyCore/Terminal/GraphemeBreakTables.swift
//   swift Scripts/gen-grapheme-tables.swift <ucd-dir> --test-data > Tests/SwifttyCoreTests/GraphemeBreakTestData.swift
//
// <ucd-dir> is a UCD tree laid out like uucode's vendored copy
// (Ghostty's zig-pkg/uucode-*/ucd): DerivedCoreProperties.txt,
// extracted/DerivedGeneralCategory.txt, auxiliary/GraphemeBreakProperty.txt,
// auxiliary/GraphemeBreakTest.txt, emoji/emoji-data.txt,
// emoji/emoji-variation-sequences.txt. Use the same Unicode version as the
// Ghostty build being mirrored.
import Foundation

let args = CommandLine.arguments.dropFirst()
guard let dir = args.first else {
    FileHandle.standardError.write("usage: gen-grapheme-tables.swift <ucd-dir> [--test-data]\n".data(using: .utf8)!)
    exit(2)
}
let ucd = URL(fileURLWithPath: dir)

func read(_ path: String) -> String {
    try! String(contentsOf: ucd.appendingPathComponent(path), encoding: .utf8)
}

func version(_ text: String) -> String {
    // First line looks like "# GraphemeBreakTest-18.0.0.txt".
    let first = text.prefix { $0 != "\n" }
    guard let dash = first.lastIndex(of: "-"), let dot = first.range(of: ".txt") else { return "unknown" }
    return String(first[first.index(after: dash) ..< dot.lowerBound])
}

/// Parses `lo..hi ; field1 ; field2 # comment` lines.
func parse(_ text: String, _ body: (ClosedRange<Int>, [String]) -> Void) {
    for line in text.split(separator: "\n") {
        let content = line.prefix { $0 != "#" }
        let fields = content.split(separator: ";").map { $0.trimmingCharacters(in: .whitespaces) }
        guard fields.count >= 2, !fields[0].isEmpty else { continue }
        let bounds = fields[0].split(separator: ".").filter { !$0.isEmpty }.map { Int($0, radix: 16)! }
        body(bounds[0] ... bounds.last!, Array(fields.dropFirst()))
    }
}

// MARK: - Test data mode

if args.contains("--test-data") {
    let text = read("auxiliary/GraphemeBreakTest.txt")
    // Scalars whose original Grapheme_Cluster_Break is Control/CR/LF. Ghostty
    // filters those before graphemeBreak, so the conformance test skips them.
    var controls = Set<Int>()
    parse(read("auxiliary/GraphemeBreakProperty.txt")) { range, f in
        if ["Control", "CR", "LF"].contains(f[0]) { for cp in range { controls.insert(cp) } }
    }
    var used = Set<Int>()
    var cases: [String] = []
    for line in text.split(separator: "\n") {
        let content = line.prefix { $0 != "#" }.trimmingCharacters(in: .whitespaces)
        guard !content.isEmpty else { continue }
        // Compact encoding: "÷" -> "/", "×" -> "x", scalars as hex.
        let tokens = content.split(separator: " ").map { tok -> String in
            switch tok {
            case "÷": "/"
            case "×": "x"
            default: String(tok)
            }
        }
        for tok in tokens where tok != "/" && tok != "x" { used.insert(Int(tok, radix: 16)!) }
        cases.append(tokens.joined(separator: " "))
    }
    print("// Generated by Scripts/gen-grapheme-tables.swift --test-data from GraphemeBreakTest-\(version(text)).txt. Do not edit.")
    print("// Each line: \"/\" = break (÷), \"x\" = no break (×), scalars in hex.")
    print("// swiftlint:disable all")
    print("")
    print("enum GraphemeBreakTestData {")
    print("    static let version = \"\(version(text))\"")
    print("    static let cases: [String] = [")
    for c in cases { print("        \"\(c)\",") }
    print("    ]")
    print("")
    print("    /// Scalars in `cases` with Grapheme_Cluster_Break Control, CR or LF.")
    let ctl = used.intersection(controls).sorted().map { String(format: "0x%04X", $0) }
    print("    static let controls: Set<UInt32> = [" + ctl.joined(separator: ", ") + "]")
    print("}")
    exit(0)
}

// MARK: - Property tables

let count = 0x110000

// Original Grapheme_Cluster_Break.
enum OGB { case other, prepend, cr, lf, control, extend, ri, spacingMark, l, v, t, lv, lvt, zwj }
var ogb = [OGB](repeating: .other, count: count)
let gbpText = read("auxiliary/GraphemeBreakProperty.txt")
parse(gbpText) { range, f in
    let value: OGB = switch f[0] {
    case "Prepend": .prepend
    case "CR": .cr
    case "LF": .lf
    case "Control": .control
    case "Extend": .extend
    case "Regional_Indicator": .ri
    case "SpacingMark": .spacingMark
    case "L": .l
    case "V": .v
    case "T": .t
    case "LV": .lv
    case "LVT": .lvt
    case "ZWJ": .zwj
    default: fatalError("unknown GCB \(f[0])")
    }
    for cp in range { ogb[cp] = value }
}

enum InCB { case none, linker, consonant, extend }
var incb = [InCB](repeating: .none, count: count)
var defaultIgnorable = [Bool](repeating: false, count: count)
parse(read("DerivedCoreProperties.txt")) { range, f in
    if f[0] == "InCB", f.count >= 2 {
        let value: InCB = switch f[1] {
        case "Linker": .linker
        case "Consonant": .consonant
        case "Extend": .extend
        default: .none
        }
        for cp in range { incb[cp] = value }
    } else if f[0] == "Default_Ignorable_Code_Point" {
        for cp in range { defaultIgnorable[cp] = true }
    }
}

var extPict = [Bool](repeating: false, count: count)
var emojiModifier = [Bool](repeating: false, count: count)
var emojiModifierBase = [Bool](repeating: false, count: count)
let emojiText = read("emoji/emoji-data.txt")
parse(emojiText) { range, f in
    switch f[0] {
    case "Extended_Pictographic": for cp in range { extPict[cp] = true }
    case "Emoji_Modifier": for cp in range { emojiModifier[cp] = true }
    case "Emoji_Modifier_Base": for cp in range { emojiModifierBase[cp] = true }
    default: break
    }
}

// General categories that matter for wcwidth_zero_in_grapheme.
enum GC { case other, cc, cs, zl, zp, mn, me }
var gc = [GC](repeating: .other, count: count)
parse(read("extracted/DerivedGeneralCategory.txt")) { range, f in
    let value: GC = switch f[0] {
    case "Cc": .cc
    case "Cs": .cs
    case "Zl": .zl
    case "Zp": .zp
    case "Mn": .mn
    case "Me": .me
    default: .other
    }
    for cp in range { gc[cp] = value }
}

var vsBase = [Bool](repeating: false, count: count)
for line in read("emoji/emoji-variation-sequences.txt").split(separator: "\n") {
    let content = line.prefix { $0 != "#" }
    let fields = content.split(separator: ";").map { $0.trimmingCharacters(in: .whitespaces) }
    guard fields.count >= 2 else { continue }
    let cps = fields[0].split(separator: " ").map { Int($0, radix: 16)! }
    if cps[1] == 0xFE0E { vsBase[cps[0]] = true }
}

// GraphemeBreakNoControl ordinals (must match GraphemeBreak.Property in Swift).
let other = 0, prepend = 1, ri = 2, spacingMark = 3, hl = 4, hv = 5, ht = 6, hlv = 7, hlvt = 8
let zwj = 9, zwnj = 10, extendedPictographic = 11, emojiModBase = 12, emojiMod = 13
let incbExtend = 14, incbLinkerExtend = 15, incbLinkerOther = 16, incbConsonant = 17

var props = [UInt8](repeating: 0, count: count)
for cp in 0 ..< count {
    // uucode GraphemeBreak component (components.zig), then NoControl folding.
    let gb: Int
    if emojiModifier[cp] {
        precondition(ogb[cp] == .extend)
        gb = emojiMod
    } else if emojiModifierBase[cp] {
        precondition(extPict[cp])
        gb = emojiModBase
    } else if extPict[cp] {
        precondition(ogb[cp] == .other)
        gb = extendedPictographic
    } else {
        switch incb[cp] {
        case .none:
            switch ogb[cp] {
            case .other, .cr, .lf, .control: gb = other
            case .prepend: gb = prepend
            case .ri: gb = ri
            case .spacingMark: gb = spacingMark
            case .l: gb = hl
            case .v: gb = hv
            case .t: gb = ht
            case .lv: gb = hlv
            case .lvt: gb = hlvt
            case .zwj: gb = zwj
            case .extend:
                precondition(cp == 0x200C, "Extend without InCB: \(String(cp, radix: 16))")
                gb = zwnj
            }
        case .extend:
            gb = cp == 0x200D ? zwj : incbExtend
        case .linker:
            gb = ogb[cp] == .extend ? incbLinkerExtend : incbLinkerOther
        case .consonant:
            gb = incbConsonant
        }
    }

    // uucode Wcwidth component (components.zig):
    //   width == 0  <=>  gc in {Cc, Cs, Zl, Zp} or (Default_Ignorable and not U+00AD)
    //   wcwidth_zero_in_grapheme = width == 0 or Emoji_Modifier or gc in {Mn, Me}
    //                              or GCB in {V, T, Prepend}
    let width0 = gc[cp] == .cc || gc[cp] == .cs || gc[cp] == .zl || gc[cp] == .zp
        || (cp != 0x00AD && defaultIgnorable[cp])
    let zero = width0 || emojiModifier[cp] || gc[cp] == .mn || gc[cp] == .me
        || ogb[cp] == .v || ogb[cp] == .t || ogb[cp] == .prepend

    props[cp] = UInt8(gb) | (zero ? 0x20 : 0) | (vsBase[cp] ? 0x40 : 0)
}

// Two-stage table; pick the block size giving the smallest total.
func build(shift: Int) -> (stage1: [Int], stage2: [UInt8]) {
    let size = 1 << shift
    var stage1: [Int] = []
    var stage2: [UInt8] = []
    var seen: [[UInt8]: Int] = [:]
    for block in 0 ..< count >> shift {
        let slice = Array(props[block << shift ..< (block + 1) << shift])
        if let index = seen[slice] {
            stage1.append(index)
        } else {
            seen[slice] = stage2.count >> shift
            stage1.append(stage2.count >> shift)
            stage2.append(contentsOf: slice)
        }
        _ = size
    }
    return (stage1, stage2)
}
var best = (shift: 0, stage1: [Int](), stage2: [UInt8]())
for shift in 5 ... 8 {
    let t = build(shift: shift)
    let bytes = t.stage1.count * 2 + t.stage2.count
    FileHandle.standardError.write("shift=\(shift) stage1=\(t.stage1.count) stage2=\(t.stage2.count) total=\(bytes)\n".data(using: .utf8)!)
    if best.stage1.isEmpty || bytes < best.stage1.count * 2 + best.stage2.count {
        best = (shift, t.stage1, t.stage2)
    }
}
precondition(best.stage2.count >> best.shift <= Int(UInt16.max))

func escape(_ bytes: [UInt8]) -> String {
    var s = ""
    for b in bytes {
        switch b {
        case 0x21 ... 0x7E where b != 0x22 && b != 0x5C: s.unicodeScalars.append(Unicode.Scalar(b))
        default: s += "\\u{\(String(b, radix: 16, uppercase: true))}"
        }
    }
    return s
}

let ucdVersion = version(gbpText)
print("// Generated by Scripts/gen-grapheme-tables.swift from UCD \(ucdVersion) (GraphemeBreakProperty,")
print("// DerivedCoreProperties InCB/Default_Ignorable, DerivedGeneralCategory, emoji-data,")
print("// emoji-variation-sequences). Do not edit.")
print("// swiftlint:disable all")
print("")
print("enum GraphemeBreakTables {")
print("    static let version = \"\(ucdVersion)\"")
print("")
print("    /// Block size is `1 << shift` scalars.")
print("    static let shift = \(best.shift)")
print("")
print("    /// Block index for each block of scalars (\(best.stage1.count) entries).")
print("    static let stage1: [UInt16] = [")
for chunk in stride(from: 0, to: best.stage1.count, by: 24) {
    print("        " + best.stage1[chunk ..< min(chunk + 24, best.stage1.count)].map { String($0) }.joined(separator: ", ") + ",")
}
print("    ]")
print("")
print("    /// \(best.stage2.count >> best.shift) unique blocks of property bytes:")
print("    /// bits 0-4 GraphemeBreak.Property, bit 5 width_zero_in_grapheme, bit 6 emoji_vs_base.")
print("    static let stage2: StaticString = \"" + escape(best.stage2) + "\"")
print("")
print("    static let stage2Count = \(best.stage2.count)")
print("}")
